[package]
name = "ch-query-analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
clickhouse = { version = "0.13.2", features = ["native-tls", "time"] }
reqwest = "0.12.15"
serde = { version = "1.0.219", features = ["derive"] }
time = "0.3.41"
tokio = { version = "1.44.2", features = ["full"] }
